export const programs = [
  "Pendidikan Dokter",
  "Pendidikan Bahasa Inggris",
  "Budidaya Perairan",
  "Pendidikan Fisika",
  "Teknik Elektro",
  "Kehutanan",
  "Ilmu Administrasi Negara",
  "Ilmu Pemerintahan",
  "Teknologi Pendidikan",
  "Pendidikan Matematika",
  "Pendidikan Guru Sekolah Dasar",
  "Pendidikan Seni Rupa",
  "Teknik Sipil / Pengairan",
  "Pendidikan Sosiologi",
  "Akuntansi",
  "Manajemen",
  "Ekonomi Pembangunan",
  "Pendidikan Bahasa dan Sastra Indonesia",
  "Agribisnis",
  "PJJ Pendidikan Guru Sekolah Dasar (TUTUP)",
  "Pendidikan Agama Islam",
  "Pendidikan Bahasa Arab",
  "Hukum Ekonomi Syari`ah (Mu`amalah)",
  "Hukum Keluarga (Ahwal Syakhshiyah)",
  "Pendidikan Pancasila dan Kewarganegaraan",
  "Profesi Dokter",
  "Komunikasi dan Penyiaran Islam",
  "Arsitektur",
  "Magister Manajemen",
  "Magister Ilmu Administrasi Publik",
  "Magister Pendidikan Bahasa Dan Sastra Indonesia",
  "Pendidikan Guru Pendidikan Anak Usia Dini",
  "Pendidikan Biologi",
  "Ekonomi Islam",
  "Ilmu Komunikasi",
  "Magister Pendidikan Islam",
  "Perpajakan", 
  "Magister Pendidikan Dasar",
  "Magister Pendidikan Bahasa Inggris",
  "Magister Agribisnis",
  "Agroteknologi",
  "Informatika",
  "Profesi Guru",
  "Kebidanan",
  "Keperawatan",
  "Farmasi",
  "Perencanaan Wilayah dan Kota",
  "Bimbingan dan Konseling Pendidikan Islam",
  "I'dad",
  "Magister Pendidikan Sosiologi",
  "Kampus Merdeka",
  "Pendidikan",
  "Hukum Bisnis",
  "Magister Pendidikan Matematika",
  "Magister Teknik Sumber Daya Air (Pengairan)",
  "Pendidikan Profesi Bidan",
  "Magister Akuntansi",
] as const

export type Program = (typeof programs)[number]
